[0m12:51:25.595615 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B184B75790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B18498A4D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B184B75090>]}
[0m12:51:25.603497 [debug] [MainThread]: An error was encountered while trying to send an event


============================== 12:51:25.603497 | b47390f9-7f9c-49fe-8e2a-3d128729d5ad ==============================
[0m12:51:25.603497 [info ] [MainThread]: Running with dbt=1.9.4
[0m12:51:25.608501 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Fatoumatta\\.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt run -s stg_orders', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:51:25.610498 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Fatoumatta\Documents\Canada\Data Engineer\sales_pipeline\data\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:51:25.613502 [debug] [MainThread]: Command `dbt run` failed at 12:51:25.613502 after 0.18 seconds
[0m12:51:25.614502 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B184BD3450>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B183E9F910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B1FE3D5DD0>]}
[0m12:51:25.615507 [debug] [MainThread]: An error was encountered while trying to send an event
[0m12:51:25.615507 [debug] [MainThread]: Flushing usage events
